### ISSUE TITLE
exe

### ISSUE THREAD

**Issue by 7f3** [hzhreal/HTOS#1]
[IMG_8254](https://github.com/hzhreal/HTOS/assets/100322527/54bd5b61-e677-47fc-abe8-4b018bdf06ce)

**Comment by hzhreal** [comment]
Hey 7f3,
If you want to wrap this code into an executable you can use pyinstaller.

Best regards,
hzhreal

**Comment by 7f3** [comment]
tried using pyinstaller, it gave my pc and ps4 fent... everything stopped working also.
