### ISSUE TITLE
Unexpected error uploading discord attachments

### ISSUE THREAD

**Issue by Noxde** [hzhreal/HTOS#2]
When trying to resign/change_title/change_picture uploading the files to discord the bot will most of the time (if not always) say "An unexpected error has occurred!" but it will work using a Google Drive link.

HTOS.log
```
[INFO|workspace|L45] 2024-05-26 - 01:35:26-0300: Folder contents of '/data/mount' deleted successfully.
[INFO|workspace|L45] 2024-05-26 - 01:35:26-0300: Folder contents of '/data/saves' deleted successfully.
[ERROR|change|L178] 2024-05-26 - 01:36:25-0300: 404 Not Found (error code: 0): asset not found - nox_23 - (unexpected)
Traceback (most recent call last):
  File "C:\Users\Mateo\Desktop\PS4 HEN\HTOS\cogs\change.py", line 166, in title
    uploaded_file_paths = await upload2(ctx, newUPLOAD_ENCRYPTED, max_files=MAX_FILES, sys_files=False, ps_save_pair_upload=True)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo\Desktop\PS4 HEN\HTOS\utils\helpers.py", line 108, in upload2
    await attachment.save(file_path)
  File "C:\Users\Mateo\Desktop\PS4 HEN\HTOS\venv\Lib\site-packages\discord\message.py", line 306, in save
    data = await self.read(use_cached=use_cached)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo\Desktop\PS4 HEN\HTOS\venv\Lib\site-packages\discord\message.py", line 348, in read
    data = await self._http.get_from_cdn(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mateo\Desktop\PS4 HEN\HTOS\venv\Lib\site-packages\discord\http.py", line 397, in get_from_cdn
    raise NotFound(resp, "asset not found")
discord.errors.NotFound: 404 Not Found (error code: 0): asset not found
```
Looks like the bot is saving the save files but then deleting them before uploading them to the PS4, I don't know though

**Comment by Noxde** [comment]
I just tried to encrypt a save and the same error happened expect when sending the decrypted save

**Comment by hzhreal** [comment]
I am aware of this and will push the fix soon. Will let you know. The issue is that the attachment is getting deleted before being saved, this caused no issues before.

**Comment by Noxde** [comment]
> I am aware of this and will push the fix soon. Will let you know. The issue is that the attachment is getting deleted before being saved, this caused no issues before.

Yea i saw that happening, just wanted to let you know. Thanks

**Comment by hzhreal** [comment]
I pushed an update, let me know if the error is fixed, it should be.

**Comment by Noxde** [comment]
> I pushed an update, let me know if the error is fixed, it should be.

Looks like its fixed now, just tried resigning and decrypting and its working fine. Thank you
